package gui;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Devin Calado
 * 
 * 
 */
public final class GameFrame extends javax.swing.JFrame {

    private ArrayList<Integer> piles;
    
    /**
     * 
     * Creates new form Main
     * @param piles         The state of the game.
     */
    public GameFrame(ArrayList piles) {
        
        this.setVisible(true);
        this.setSize(800, 600);
        this.setAlwaysOnTop(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      
        this.piles = piles;
        
        this.validate();
        
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 20));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("MainFrame"); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paint(Graphics g) {
        super.paint(g);
    
        for (int i = 1; i <= piles.size(); i++) {
            g.setColor(Color.BLUE);
            g.fillRect(i * 60, 200, 90,60);
            g.setColor(Color.red);
            g.drawString(piles.get(i).toString(), i * 60, 200);
        }
    }
    
    
    public void setPiles(ArrayList piles ){
        this.piles = piles;
    }
    
    public void update() {
        this.repaint();//Refresh the graphics view
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
